name: local_to_remote_feature_branch_validation

on:  
  push:
    branches:
      - 'feature*'
      - 'dev'
      - 'main'

  pull_request:
    branches:
      - 'main'

jobs:
  push_check:-
    name: push_from local_to_feature_check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Check commit messages
        uses: actions/checkout@v2

      - name: Validate commit messages
        run: |
          COMMIT_MSG=$(git log --format=%B -n 1 $GITHUB_SHA)
          if [[ ! "$COMMIT_MSG" =~ ^JIRA* ]]; then
            echo "Commit message must start with Jira number, e.g. 'JIRA123'."
            exit 1
          fi
      - name: Set up python
        uses: actions/setup-python@v3

      - name: install dependencies
        run: | 
          pip install flake8

      - name: run lint test
        working-directory: ./src
        run: |
          flake8 hello.py

      


